services:
  db:
    image: postgres:15-alpine
    container_name: soulbreach-db
    environment:
      POSTGRES_USER: user_soul
      POSTGRES_PASSWORD: password_breach
      POSTGRES_DB: soul_breach_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

  pgadmin:
    image: dpage/pgadmin4
    container_name: soulbreach-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@soulbreach.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: